# Starter pipeline   
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
    
- task: EmailReport@1
  inputs:
    sendMailConditionConfig: 'Always'
    subject: 'test subject'
    toAddress: 'michal.jeleniasty@gmail.com;mjelen@freeportmetrics.com'
    defaultDomain: 'microsoft.com'
    groupTestResultsBy: 'run'
    includeCommits: false
    maxTestFailuresToShow: '15'
    includeOthersInTotal: false
    usePreviousEnvironment: false
    smtpConnectionEndpoint: 'SMTPForEmailReportTaskTest'
    
